travis:
  secure:
    BINSTAR_TOKEN: XqPu06rAdW4yLgxcdRzYWttzv150ggPL3w4m2O0MJMX7KiX437Ke9HnVf816jvF/9m3WuxlVyvQmH0kFknHFw5GUCtU04Md8D++0jwumIyjw4sjxv48oz4Jlm4vFmBqaDBmpwWYEG+gISWPRiSooRbmjbJTcoz5bb0MIniDJe6F7M67jYH2mD0KhKfAiSQ1GXGa1RIQS92Hnh1qIEIEOi2HgI4tc0CgcC+JHoCxYuRaIA9HoZFZHIq0IYBC+9pkALS+hj9obvbekSIBYluZll0A2fi/2i4456DhmgP6+Ipx2LBQH9N5r5OUucl3QDoshPjWoEpEnN3feVcqkTGry82IYvuVR9p8seHJfJ5U13ecqxWot64XdWQoOJEQVAdrtEKYryoeJPeUiHbYEiIW+fTWC3CDtt2QgaiQTBQz5QRtkiVvhGgDhFRjtpiqD2j8G6nkfmUpscVTTV4awM/p/yNdUEuNijGz13LzLTl4/6CynrrMewuVUOWX3BxS1RG2w+1ONii1BnS3K0LGTX1ex9aU+rSmqvwaoDiJQWdfiCb6qd8kz8yAlpRdGWCjG6coHgi6Sh6yoIdacQZPBofBYW7Kcy48ASrNf3cy4hjmxuNqwz8nG2ptwUAuzFMLnmSFZK7BTg2BC7DmMJzgkAfPprMmaTok4e9Q51Ar2VYUGuyA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
