travis:
  secure:
    BINSTAR_TOKEN: xBx1cUUdtxnC/bHe9uvEv+TfzxxrMCOk3ixEBaTLBziLv9wPkuBMA0sLFS5vo0cuyyfWhTotMPGFBFk8Rcfnfhw+XHg+A9LZRPZ3wUhikrXCuHOy4dLYoBpOzwkoUG75AUGbEXZQDUT0Efv+uM404f+fwAtc32usZGaZNIgE3dRjeMwKhHNikTDuJcs7bIRw0IpcaEpuxqHJDZShPSU8ToLRbbJ4pPM28ypZjCOhAafJEJYyvWeMEbktSgydn4zLslXsqG7Rfx4SjkIf9cX17vOr3RGdjIXX8+VoIAWk7rkBqqBo3PVcTkfe+1IwK3rV11vE/8h1Gf6OTJqaBbRdrSVDBbC4boi0GWRnBZkMlPL46UTd0Dc4iarR6G44oZ/FQLTvAP65BRf0lhdSZmEEvV36Wnjbt+11zw33S8Hu0waa/KD73807AOb3lyRBw5MnqLVQVbjrOfRny/D07mpQLfmcLd6PhLsh7vPaD8OoeRAVc4Nbb80LIiY3/kkXOVvnqrdIVQlYVNVoCAC5IDco72BGKVOc1icARe5N3HjVNZsKJmhHI4qmVXAKxFAOsh+AGnVTRciOY9Bd3+3Sr+0ANZp6LuhMhh0wF4GltsI22s2E7tdhZ4zk22bIjhFf0TcCiHcX8xB+pvQWP/wDOjqcVC+ebrCgvkV1r7DGuo2OtNY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
